---
- name: OCP4 Registry | registry-init | Tar registry and nginx containers from local dir
  find:
    paths: 

- name: OCP4 Registry | registry-init | Copy registry content to registry node
  copy:
    src: "{{ nameVpc }}-bastion-node.tar"
    dest: /tmp

- name: OCP4 Registry | registry-init | Unarchive the tarball
  unarchive:
    src: "/tmp/{{ nameVpc }}-bastion-node.tar"
    dest: 
