---
- name: ocp4-deploy | task03-deploy | Stash deployment docker images
  command: "{{ item }}"
  with_items:
    - podman pull docker.io/library/registry:2
    - podman pull docker.io/library/nginx:latest
    - podman pull docker.io/library/containercraft/one:4.3.8
  register: images
  when: "'Image is up to date' not in images.stdout"

# ToDO: This is not idempotent - will report "changed" every run
- name: ocp4-deploy | task03-deploy | Export images
  command: "{{ item }}"
  with_items:
    - podman save -o docker-registry2-image.tar registry:2
    - podman save -o docker-nginxlatest-image.tar nginx:latest
    - podman save -o docker-containerone-image.tar containercraft/one:4.3.8
  args:
    chdir: "{{ home_directory }}/PlatformOne/images/"

- name: ocp4-deploy | task03-deploy | Download openshift images for registry
  block:
    - name: ocp4-deploy | task03-deploy | Check for file existence
      find:
        file_type: directory
        paths: "{{ base_directory }}/mirror"
      register: files

    - name: ocp4-deploy | task03-deploy | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent
      when: files.examined > 0 

    - name: ocp4-deploy | task03-deploy | Create task03-deploy mirror directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ base_directory }}/mirror"
        - "{{ home_directory }}/.docker"

    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror

# Rescue block if there are any failures in the above block
  rescue:
    - name: ocp4-deploy | task03-deploy | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent

    - name: ocp4-deploy | task03-deploy | Create registry mirror directory
      file:
        path: "{{ base_directory }}/mirror"

    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror
      register: mirror

- name: ocp4-deploy | task03-deploy | Additional rescue block run for mirror sync
  block:
    - name: ocp4-deploy | task03-deploy - extra rescue | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent

    - name: ocp4-deploy | task03-deploy - extra rescue | Create registry mirror directory
      file:
        path: "{{ base_directory }}/mirror"

    - name: ocp4-deploy | task03-deploy - extra rescue | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror
  when: "'Error' in mirror.stdout or 'error' in mirror.stdout  or 'ERROR' in mirror.stdout"

#This tarball is used in the next task for uploading images to container registry
- name: ocp4-deploy | task03-deploy | Archive images and artifacts
  command:
    "tar -cvzf {{ home_directory }}/PlatformOne.tar.gz \
     -C {{ home_directory }} PlatformOne"
  args:
    creates: "{{ home_directory }}/PlatformOne.tar.gz"
