---
- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0775'
    recurse: yes
  with_items:
    - '{{ dir_platform }}/terraform'
    - '{{ dir_koffer }}/bundle'
    - '{{ dir_platform }}/ansible'
    - '{{ dir_platform }}/mirror'
    - '{{ dir_platform }}/images'
    - '{{ dir_platform }}/nginx'
    - '{{ dir_platform }}/secrets'
    - '{{ dir_platform }}/secrets/ssh'
    - '{{ dir_platform }}/secrets/registry'
    - '{{ dir_platform }}/secrets/registry/ssl'
    - '{{ dir_platform }}/secrets/registry/auth'

- name: '{{ ansible_name_module }} | template | Stage CloudCtl Startup Assets' 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '0775', src: '{{ dir_koffer }}/templates/bin/answer.sh.j2', dest: '/tmp/answer.sh' }
    - { mode: '0775', src: '{{ dir_koffer }}/templates/bin/konductor.sh.j2', dest: '/tmp/konductor.sh' }
    - { mode: '0775', src: '{{ dir_koffer }}/templates/pod/cloudctl.yml.j2', dest: '/tmp/cloudctl.yml' }
    - { mode: '0775', src: '{{ dir_koffer }}/templates/registry/etc-docker-registry-config.yml.j2', dest: '/root/deploy/mirror/config.yml' }
