#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ ansible_name }} | coredns.yml' 
  hosts: cloudctl
  become: true
  become_user: root
  vars_files:
    - '../cluster-vars.yml'
    - 'vars/global.yml'
    - 'vars/coredns.yml'
  vars:
    module: "coredns"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    dns_zone: "{{ {{ domain_cluster }} | default(sparta.codectl.io) }}"
  roles:
    - role: coredns
      when: coredns == true
