#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: 'RedHat | Konductor | ignition' 
  hosts: konductor
  vars_files:
    - '../cluster-vars.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "ignition"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - ignition

- name: 'RedHat | cloudctl | Restart nginx Container' 
  hosts: cloudctl
  become: yes
  tasks:
    - name: 'RedHat | cloudctl | Restart nginx Container'
      podman_container:
        name: nginx
        state: started
        force_restart: yes