---
- name: ocp4-deploy | Install and Configure OCP4
  hosts: localhost
  connection: local
  tasks: 
    - name: ocp4-deploy | Import OCP4 deploy role
      include_role: ./roles/task03-deploy
      tags:
        - deploy
