---
- name: ocp4-deploy | Install registry artifacts on Platform0ne
  hosts: localhost
  connection: local
  roles:
    - task03-deploy

- name: ocp4-deploy | Install registry on registry node
  hosts: registry
  become: true
  roles:
    - task03-deploy