#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ name_vendor }} | Koffer | tree.yml' 
  hosts: local
  vars_files:
    - 'vars/global.yml'
#   - 'vars/git.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file | Create Directory Structure' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ dir_platform }}/config/user-data'
        - '{{ dir_platform }}/cluster/manifests'
        - '{{ dir_platform }}/cluster/ignition'
        - '{{ dir_platform }}/cluster/aux'
        - '{{ dir_platform }}/cluster/aux/manifests'
        - '{{ dir_platform }}/cluster/aux/openshift'
        - '{{ dir_platform }}/cluster/config'
        - '{{ dir_platform }}/cluster/'
        - '{{ dir_platform }}/terraform'
        - '{{ dir_platform }}/ansible'
        - '{{ dir_platform }}/mirror'
        - '{{ dir_platform }}/images'
        - '{{ dir_platform }}/nginx'
    - file:
        path: '{{ item }}'
        state: directory
        mode: '0644'
      with_items:
        - '{{ dir_platform }}/secrets/registry/ssl'
        - '{{ dir_platform }}/secrets/registry/auth'
        - '{{ dir_platform }}/secrets/cluster'
        - '{{ dir_platform }}/secrets/docker'
        - '{{ dir_platform }}/secrets/aws'
        - '{{ dir_platform }}/secrets/ssh'
        - '{{ local_home }}/.kube'
