---
- name: '{{ plugin.name }} | role:{{ plugin.role }} | git:clone | Clone Git Dependencies' 
  git:
    clone: yes
    force: yes
    update: true
    repo: "{{ item.value.url }}"
    version: "{{ item.value.ref }}"
    dest: "{{ item.value.dest }}"
  with_dict:
    - "{{ git }}"
  when:
    - item.value.url is defined

- name: '{{ plugin.name }} | role:{{ plugin.role }} | shell:terraform.init | Initilize terraform modules'
  shell: 
    cmd: terraform init
    chdir: "{{ item.value.dest }}"
  with_dict:
    - "{{ git }}"
  when:
    - item.value.tfinit and item.value.url is defined
