---
- name: '{{ plugin.name }} | role:{{ plugin.role }} | git:clone | Clone Git Dependencies' 
  git:
    clone: yes
    repo: "{{ item.repo }}"
    version: "{{ item.branch }}"
    dest: "{{ item.dest }}"
    update: true
    force: yes
  with_items:
    - "{{ git.sparta }}"
    - "{{ terraform }}"

- name: '{{ plugin.name }} | role:{{ plugin.role }} | shell:terraform.init | Initilize terraform modules'
  shell: 
    cmd: terraform init
    chdir: "{{ item.dest }}"
  with_items:
    - "{{ terraformrepos }}"
