---
- name: '{{ plugin.name }} | role:{{ plugin.role }} | file:absent | Clean artifact staging space'
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ dir.platform }}'
  when: not koffer.omnibus

- name: '{{ plugin.name }} | role:{{ plugin.role }} | file:directory | Create Artifact Directory Tree' 
  file:
    state: directory
    path: '{{ item }}'
    recurse: no
    mode: '0666'
  with_items:
    - '{{ dir.tmp }}'
    - '{{ dir.iac }}'
    - '{{ dir.meta }}'
    - '{{ dir.bundle }}'
    - '{{ dir.platform }}'
