---
- name: ocp4-deploy | tf-vars-create | Register AWS access key IF
  shell: "cat ${dirArtifacts}/.aws/govcloud.credentials | grep aws_access_key_id | awk '{print $3}'"
  register: aws_access_key

- name: ocp4-deploy | tf-vars-create | Register AWS secret access key
  shell: "cat ${dirArtifacts}/.aws/govcloud.credentials | grep aws_secret_access_key | awk '{print $3}'"
  register: aws_secret_key

- set_fact:
    aws_access_key_id: "{{ aws_access_key.stdout }}"
    aws_secret_access_key: "{{ aws_secret_key.stdout }}"
  no_log: true

- name: ocp4-deploy | tf-vars-create | Create terraform variables file
  template:
    src: tf-vars.tf.j2
    dest: "{{ base_directory }}/terraform/tf-vars.tf"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: 0755
